services:
  - type: web
    name: image-uploader
    env: node
    repo: https://github.com/connectshark/image-uploader.git
    region: singapore
    plan: free
    branch: main
    healthCheckPath: /healthz
    startCommand: npm run start
    buildCommand: npm install
    envVars:
    # - fromGroup: imgur-api
    - key: IMGUR_ALBUM_ID
      sync: false
    - key: IMGUR_CLIENT_ID
      sync: false
    - key: IMGUR_CLIENT_SECRET
      sync: false
    - key: IMGUR_REFRESH_TOKEN
      sync: false
  - type: web
    name: image-manager
    env: static
    repo: https://github.com/connectshark/image-manager.git
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_DOMAIN
        fromService:
          type: web
          name: image-uploader
          property: host
    routes:
      - type: rewrite
        source: /*
        destination: /index.html